#pragma once

#include "sdkconfig.h"

#ifndef CONFIG_UART_MGR_SPI_HOST
#define BOARD_SPI_HOST 2
#else
#define BOARD_SPI_HOST CONFIG_UART_MGR_SPI_HOST
#endif

#ifndef CONFIG_UART_MGR_SPI_MOSI_GPIO
#define BOARD_SPI_MOSI_GPIO 9
#else
#define BOARD_SPI_MOSI_GPIO CONFIG_UART_MGR_SPI_MOSI_GPIO
#endif

#ifndef CONFIG_UART_MGR_SPI_MISO_GPIO
#define BOARD_SPI_MISO_GPIO 8
#else
#define BOARD_SPI_MISO_GPIO CONFIG_UART_MGR_SPI_MISO_GPIO
#endif

#ifndef CONFIG_UART_MGR_SPI_SCLK_GPIO
#define BOARD_SPI_SCLK_GPIO 7
#else
#define BOARD_SPI_SCLK_GPIO CONFIG_UART_MGR_SPI_SCLK_GPIO
#endif

#ifndef CONFIG_UART_MGR_SPI_CS0_GPIO
#define BOARD_SPI_CS0_GPIO 10
#else
#define BOARD_SPI_CS0_GPIO CONFIG_UART_MGR_SPI_CS0_GPIO
#endif

#ifndef CONFIG_UART_MGR_SPI_CS1_GPIO
#define BOARD_SPI_CS1_GPIO 11
#else
#define BOARD_SPI_CS1_GPIO CONFIG_UART_MGR_SPI_CS1_GPIO
#endif

#ifndef CONFIG_UART_MGR_SPI_CLOCK_HZ
#define BOARD_SPI_CLOCK_HZ 10000000
#else
#define BOARD_SPI_CLOCK_HZ CONFIG_UART_MGR_SPI_CLOCK_HZ
#endif

#ifndef CONFIG_UART_MGR_GPIO_IF_SEL_A
#define BOARD_GPIO_IF_SEL_A 12
#else
#define BOARD_GPIO_IF_SEL_A CONFIG_UART_MGR_GPIO_IF_SEL_A
#endif

#ifndef CONFIG_UART_MGR_GPIO_IF_SEL_B
#define BOARD_GPIO_IF_SEL_B 13
#else
#define BOARD_GPIO_IF_SEL_B CONFIG_UART_MGR_GPIO_IF_SEL_B
#endif

#ifndef CONFIG_UART_MGR_GPIO_CS_GROUP1
#define BOARD_GPIO_CS_GROUP1 14
#else
#define BOARD_GPIO_CS_GROUP1 CONFIG_UART_MGR_GPIO_CS_GROUP1
#endif

#ifndef CONFIG_UART_MGR_GPIO_CS_GROUP2
#define BOARD_GPIO_CS_GROUP2 15
#else
#define BOARD_GPIO_CS_GROUP2 CONFIG_UART_MGR_GPIO_CS_GROUP2
#endif

#ifndef CONFIG_UART_MGR_GPIO_CS_GROUP3
#define BOARD_GPIO_CS_GROUP3 16
#else
#define BOARD_GPIO_CS_GROUP3 CONFIG_UART_MGR_GPIO_CS_GROUP3
#endif

#ifndef CONFIG_UART_MGR_GPIO_CS_GROUP4
#define BOARD_GPIO_CS_GROUP4 17
#else
#define BOARD_GPIO_CS_GROUP4 CONFIG_UART_MGR_GPIO_CS_GROUP4
#endif

#ifndef CONFIG_UART_MGR_XTAL_HZ
#define BOARD_XR20_UART_CLOCK_HZ 24000000
#else
#define BOARD_XR20_UART_CLOCK_HZ CONFIG_UART_MGR_XTAL_HZ
#endif
